### ISSUE TITLE
Factor 10 in RICE social welfare function

### ISSUE THREAD

**Issue by FrankErrickson** [Environment-Research/Utilitarianism#4]
@davidanthoff mentioned the modified social welfare function component we have misses a multiplication by 10 for the utility flow per time period. Still a question if we need a new welfare component for RICE. @fdennig

**Comment by davidanthoff** [comment]
I believe with https://github.com/anthofflab/MimiRICE2010.jl/pull/18 we probably don't need a separate SWF in this repo anymore?

**Comment by fdennig** [comment]
Whatever is faster is fine by me. no idea what happens in  anthofflab/MimiRICE2010.jl#18, but we can go that way, or keep it this way. Welfare numbers are not reported anywhere, and there is no convention for what the correct welfare function should be. Its like measuring consumption in different units. we could measure them in dollars instead of thousands of dollars, and that would not make the results any more or less correct. crucially, removing or adding a factor 10 does not change any results. whichever way we can get a repository online by early next week is how we should go.
